export const demoCourse = [
  {
    id: 1,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "Web IT Institute",
    rating: 4.8,
    date: "20 Apr - 31 Sep",
    seats: 30,
    price: 250,
  },
  {
    id: 2,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 3,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 4,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 5,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 250,
  },
  {
    id: 6,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 7,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 8,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 9,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
  {
    id: 10,
    coverImage: "https://i.ibb.co.com/0X7d9cd/course-card-cover.png",
    title: "Mastering JavaScript: The Complete Guide",
    description:
      "Learn JavaScript from scratch and build dynamic, interactive web applications. Perfect for beginners and intermediate learners.",
    authorImage: "https://i.ibb.co.com/7nph2DF/author-image.png",
    authorName: "John Doe",
    rating: 4.8,
    date: "2024-12-15",
    seats: 30,
    price: 49.99,
  },
];